repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml

- repo: https://github.com/psf/black
rev: 22.1.0
hook:
- id: black

- repo: https://github.com/pre-commit/mirrors-mypy
rev:  v0.931
hooks:
- id: mypy

- repo: https://github.com/PyCQA/isort
rev:  5.10.1
hooks:
- id: isort